### ISSUE TITLE
[BUG] 无法下载日志

### ISSUE THREAD

**Issue by lotustalk** [wwwpf/QzoneExporter#16]
使用平台为windows 10 x64

下载运行导出之后，到1700多篇的时候停止

sleep 0.40s
'NoneType' object is not subscriptable
done

无法继续，不知道是啥原因

**Comment by wwwpf** [comment]
代码报错在哪一行？

**Comment by lotustalk** [comment]
'NoneType' object is not subscriptable
done
报完这个就停止了，程序自动退出了，我是在powershell 使用，Python 3.5.2 |Anaconda 4.2.0 (64-bit)

**Comment by wwwpf** [comment]
光凭这个无法判断出错原因，我这边也无法复现，你可以本地调试下。

**Comment by lotustalk** [comment]
2019-05-25 15:59:42,607 tools.py[line:74]	ERROR	'data'
Traceback (most recent call last):
  File "E:\QzoneExporter\QzoneExporter-master\tools.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "exporter.py", line 718, in _get_like_data
    like_count = unikey_json_data["data"][0]["current"]["likedata"]["cnt"]
KeyError: 'data'
2019-05-25 15:59:42,616 connectionpool.py[line:805]	INFO	Starting new HTTPS connection (1): h5.qzone.qq.com
2019-05-25 15:59:42,954 tools.py[line:74]	ERROR	'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "E:\QzoneExporter\QzoneExporter-master\tools.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "exporter.py", line 203, in _get_blog_data
    new_data = statistical_json_data["data"][0]["current"]["newdata"]
TypeError: 'NoneType' object is not subscriptable

这是日志里面的报错内容 大佬看看是否有啥提示

**Comment by wwwpf** [comment]
返回的点赞数据有问题，可以忽略掉这些数据

**Comment by lotustalk** [comment]
嗯哪有办法只下载日志，不需要说说点赞阅读数之类的嘛，我删了相关代码不过一直报错，求大佬指点

**Comment by wwwpf** [comment]
把最新的代码中的`_get_like_data`函数改成
```python
@logging_wrap
def _get_like_data(self, unikey):
    return None
```
