### ISSUE TITLE
albumListModeSort'

### ISSUE THREAD

**Issue by loooo139** [wwwpf/QzoneExporter#2]
2018-08-01 11:43:36,978 tools.py[line:19]	ERROR	'albumListModeSort'
Traceback (most recent call last):
  File "D:/qzone/QzoneExporter\tools.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "D:/qzone/QzoneExporter/exporter.py", line 412, in _get_list_album_data
    if not json_data["data"]["albumListModeSort"]:
KeyError: 'albumListModeSort'
请问这个是哪里出错了啊

**Comment by loooo139** [comment]
log里面我看了就是这个错误，返回的json里面没有这个key。代码里面没有注释，我也不知道这个确切的意思，是腾讯改了借口还是怎么回事？

**Comment by wwwpf** [comment]
这是在点击“相册”的时候浏览器发送的请求，然后服务器会返回一个相册的列表，你换个目标QQ号也是这种情况吗？

**Comment by loooo139** [comment]
我测试别的qq号码还是不行，还报错。
2018-08-01 22:07:52,136 exporter.py[line:411]	WARNING	albumListModeSort not found in {'albumListModeClass': [{'albumList': [{'allowAccess'
json的data下只有albumListModeClass

**Comment by wwwpf** [comment]
去QQ空间把相册的展示设置改成普通视图就好
