### ISSUE TITLE
[BUG]下载说说，62页有8页报错 附错误代码

### ISSUE THREAD

**Issue by eallion** [wwwpf/QzoneExporter#22]
```
Traceback (most recent call last):
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eallion/shuosuo/QzoneExporter-master/displayer.py", line 57, in shuoshuo
    return generator.generate_shuoshuo(page)
  File "/home/eallion/shuosuo/QzoneExporter-master/generator.py", line 269, in generate_shuoshuo
    **self._template_args)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/eallion/.local/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/eallion/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/eallion/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/eallion/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eallion/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/eallion/shuosuo/QzoneExporter-master/html/templates/shuoshuo.html", line 7, in top-level template code
    {% from "tools.html" import shuoshuo_comment_content %}
  File "/home/eallion/shuosuo/QzoneExporter-master/html/templates/index_base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/eallion/shuosuo/QzoneExporter-master/html/templates/base.html", line 39, in top-level template code
    {% block content %}
  File "/home/eallion/shuosuo/QzoneExporter-master/html/templates/shuoshuo.html", line 40, in block "content"
    {% include "shuoshuo_md.html" %}
  File "/home/eallion/shuosuo/QzoneExporter-master/html/templates/shuoshuo_md.html", line 3, in top-level template code
    {% set media_list = msg | get_shuoshuo_media_list(uin, download_if_not_exist) %}
  File "/home/eallion/shuosuo/QzoneExporter-master/template_filters.py", line 376, in get_shuoshuo_media_list
    download_if_not_exist, shuoshuo=True)
  File "/home/eallion/shuosuo/QzoneExporter-master/template_filters.py", line 349, in get_media_list
    for media_info in media_info_list:
TypeError: 'NoneType' object is not iterable
```

**Comment by wwwpf** [comment]
这是在网页显示时候报的错误，通过 exporter.py 下载的时候有错误吗？
对应说说的 json 数据发出来看看，把个人数据替换掉。

**Comment by eallion** [comment]
> 这是在网页显示时候报的错误，通过 exporter.py 下载的时候有错误吗？
> 对应说说的 json 数据发出来看看，把个人数据替换掉。

对的，是显示网页的时候报错。
json数据我通过excel处理好后已经删除了。

大致看了下，应该是json对齐格式有问题，而json对齐比较严格。下载的json数据是完整的，显示出错的json通过notepad++打开后，复制到excel里，content一列会跑到很右边（具体列数也不一定，但正确的基本上都在第E还是F列）。
引起这个的原因，初步怀疑可能是因为某一篇说说的回复数太多导致。这一条只是建议方向。

**Comment by wwwpf** [comment]
可能是某些外部引用的视频没有 video_id 导致的。
