### ISSUE TITLE
展示空间出错

### ISSUE THREAD

**Issue by Stanla** [wwwpf/QzoneExporter#25]
**Describe the bug**
使用displayer.py展示数据时访问出错

**To Reproduce**
- pip3 install requests
- pip3 install bs4
- pip3 install flask
- pip3 install piexif
- edit the exporter.py
- python3 exporter.py --all
- python3 displayer.py

**Expected behavior**
DIsplay the data properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/15817126/60013753-d21cee80-96b1-11e9-8d20-9e2fb6bf8d14.png)

**Additional context**
```
**shell:**
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/QzoneExporter/displayer.py", line 58, in shuoshuo
    return generator.generate_shuoshuo(page)
  File "/root/QzoneExporter/generator.py", line 269, in generate_shuoshuo
    **self._template_args)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/local/lib/python3.5/dist-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/root/QzoneExporter/html/templates/shuoshuo.html", line 7, in top-level template code
    {% from "tools.html" import shuoshuo_comment_content %}
  File "/root/QzoneExporter/html/templates/index_base.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/QzoneExporter/html/templates/base.html", line 39, in top-level template code
    {% block content %}
  File "/root/QzoneExporter/html/templates/shuoshuo.html", line 27, in block "content"
    <pre style="display:inline;" class="content">{{msg["content"]|content_beautify|safe}}</pre>
  File "/root/QzoneExporter/template_filters.py", line 71, in content_beautify
    s = s.replace(m[0],
TypeError: '_sre.SRE_Match' object is not subscriptable
```
注，目标空间部分相册上锁，空间访问不受限。
爬取数据时得到"done"

**Comment by wwwpf** [comment]
更新 Python 到 3.6 及以上版本
或者
将 `m[n]` 换成 `m.group(n)`
