### ISSUE TITLE
打开空相册报错，这是最后的一个相册，也是一个空相册

### ISSUE THREAD

**Issue by softshield** [wwwpf/QzoneExporter#36]
Traceback (most recent call last):
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\xiebing\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\xiebing\Desktop\QzoneExporter-master\displayer.py", line 111, in photo
    return generator.generate_photo(encoded_album, page)
  File "C:\Users\xiebing\Desktop\QzoneExporter-master\generator.py", line 373, in generate_photo
    album_id, album_dir = self.get_album_id_dir(encoded_album)
  File "C:\Users\xiebing\Desktop\QzoneExporter-master\generator.py", line 539, in get_album_id_dir
    album_id = self._ablum_name2id[encoded_album]
KeyError: '摄影日记'

**Comment by wwwpf** [comment]
json 数据有这个相册但没对应文件夹吗？

**Comment by softshield** [comment]
> json 数据有这个相册但没对应文件夹吗？

对的，目录中没有文件夹，JSON有数据。
