### ISSUE TITLE
不报错但是下载的json是空的

### ISSUE THREAD

**Issue by Siriuscw** [wwwpf/QzoneExporter#4]
![image](https://user-images.githubusercontent.com/13619509/45592665-772dcc80-b9a6-11e8-8e8e-77171c99853b.png)
返回了个code是什么意思呢

**Comment by Siriuscw** [comment]
![image](https://user-images.githubusercontent.com/13619509/45592686-fc18e600-b9a6-11e8-8366-3e3ea7d2fe86.png)

**Comment by wwwpf** [comment]
需要先指定--photo选项把数据抓下来
`python exporter.py --photo`
然后下载
`python exporter.py --download`。
或者
`python exporter.py --photo --download`

**Comment by Siriuscw** [comment]
还是不行呢，也是返回‘code然后json为空

**Comment by wwwpf** [comment]
有访问权限吗？相册或者说说的json数据是空的吗？

**Comment by Siriuscw** [comment]
有权限的，点进去看见是有内容的

**Comment by wwwpf** [comment]
本地有保存相册的json数据吗

**Comment by Siriuscw** [comment]
每次运行前都清了的。

**Comment by wwwpf** [comment]
`python exporter.py --photo --download`这个试过吗

**Comment by Siriuscw** [comment]
2018-09-16 15:33:09,662 account_info.py[line:72]	ERROR	get request failed
NoneType: None
2018-09-16 15:33:09,662 tools.py[line:28]	ERROR	Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\hu\gitDL\Qzone\tools.py", line 26, in get_json_data_from_response
    return json.loads(s)
  File "D:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-09-16 15:33:09,665 tools.py[line:29]	ERROR	=====
to json error: 
=====
Traceback (most recent call last):
  File "C:\Users\hu\gitDL\Qzone\tools.py", line 26, in get_json_data_from_response
    return json.loads(s)
  File "D:\python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-09-16 15:33:09,666 exporter.py[line:111]	INFO	save main page data to 1064988050\1064988050_main_page.json
2018-09-16 15:33:09,667 tools.py[line:19]	ERROR	'code'
Traceback (most recent call last):
  File "C:\Users\hu\gitDL\Qzone\tools.py", line 16, in wrapper
    return func(*args, **kwargs)
  File "exporter.py", line 113, in _get_main_page_data
    if main_json_data["code"] != 0:
KeyError: 'code'
2018-09-16 15:33:09,669 download.py[line:101]	WARNING	1064988050\shuoshuo\to_download.txt not exists
2018-09-16 15:33:09,669 download.py[line:101]	WARNING	1064988050\photo\to_download.txt not exists

**Comment by Siriuscw** [comment]
![image](https://user-images.githubusercontent.com/13619509/45594028-f1217e00-b9c5-11e8-9c4c-56cc9e4f9396.png)

**Comment by wwwpf** [comment]
返回的json数据有问题，main_page.json里面的内容是什么

**Comment by wwwpf** [comment]
F12看一下readme里面的那个main_page请求对应的响应，有数据吗？

**Comment by Siriuscw** [comment]
![image](https://user-images.githubusercontent.com/13619509/45822740-b8173f80-bd1e-11e8-853b-f1ee3264353e.png)
有呢qwqqq

**Comment by Siriuscw** [comment]
诶？突然就可以了？
我就几天没上2333

**Comment by wwwpf** [comment]
敏感信息给你删掉了。
