### ISSUE TITLE
[BUG]display的照片选项点了报错

### ISSUE THREAD

**Issue by CberYellowstone** [wwwpf/QzoneExporter#43]
不是全部报错,只是一部分人的会报错
报错时会有个网页
这是网页的内容
下面附上了网页的截图

个人猜测是空相册在作怪

TypeError
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last)
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib64/python3.6/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/root/Jupyter/QzoneExpoter/displayer.py", line 99, in album
return generator.generate_photo()
File "/root/Jupyter/QzoneExpoter/generator.py", line 363, in generate_photo
self._init_album_info()
File "/root/Jupyter/QzoneExpoter/generator.py", line 452, in _init_album_info
for album in temp:
TypeError: 'NoneType' object is not iterable
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
![FireShot Capture 023 - TypeError_ 'NoneType_ - https___yellow-stone tpddns cn_5001_3259403948_photo_](https://user-images.githubusercontent.com/37031767/70861058-49965100-1f64-11ea-9b4c-883b753578ae.png)

**Comment by wwwpf** [comment]
对应相册下的 json 文件里，`["data"]["albumListModeSort"]` 有数据吗？

**Comment by CberYellowstone** [comment]
{
    "code": 0,
    "subcode": 0,
    "message": "",
    "default": 0,
    "data": {
        "albumListModeSort": null,
        "albumsInUser": 0,
        "classList": [
            {
                "id": 100,
                "name": "最爱"
            },
            {
                "id": 101,
                "name": "人物"
            },
            {
                "id": 102,
                "name": "风景"
            },
            {
                "id": 103,
                "name": "动物"
            },
            {
                "id": 104,
                "name": "游记"
            },
            {
                "id": 105,
                "name": "卡通"
            },
            {
                "id": 106,
                "name": "生活"
            },
            {
                "id": 107,
                "name": "其他"
            }
        ],
        "limit": 0,
        "mode": 2,
        "nextPageStartModeSort": 0,
        "sortOrder": 1,
        "t": "",
        "totalInPageModeSort": 0,
        "user": {
            "diskused": "247.23",
            "microalbum": 0,
            "mspec": 1,
            "ordermode": 0,
            "ordertype": 1,
            "ownerface": 1,
            "preurlspec": "i",
            "time": 1576400074,
            "userbit": 0
        }
    }
}

**Comment by CberYellowstone** [comment]
@wwwpf 
![蜂蜜浏览器_蜂蜜浏览器_新建位图图像](https://user-images.githubusercontent.com/37031767/71248812-c6576f80-2356-11ea-9483-dc2d9210e845.jpg)
这就是photo文件夹里的所有内容,文件详情也贴上去了
